/* 原创角色沈晚。同一张脸，100 套衣服按日期轮换。胸更大，腰和腿保持细。 */
const OUTFITS = [
  { name: "深灰高领，黑风衣", file: "outfit-01.png" },
  { name: "白衬衫，墨蓝背心裙", file: "outfit-02.png" },
  { name: "藏蓝开衫，浅灰内搭", file: "outfit-03.png" },
  { name: "黑裙，细银链", file: "outfit-04.png" },
  { name: "米白衬衫，深棕长裤", file: "outfit-05.png" },
  { name: "墨绿针织裙，短黑外套", file: "outfit-06.png" },
  { name: "浅灰卫衣，敞着的深蓝衬衫", file: "outfit-07.png" },
  { name: "黑高领，驼色开衫", file: "outfit-08.png" },
  { name: "立领白衬衣，炭灰马甲", file: "outfit-09.png" },
  { name: "酒红内搭，黑外套长裙", file: "outfit-10.png" },
  { name: "雾蓝衬衫裙，深色腰带", file: "outfit-11.png" },
  { name: "细条纹衬衫，焦糖开襟毛衣", file: "outfit-12.png" },
  { name: "全黑套装，小银耳钉", file: "outfit-13.png" },
  { name: "深紫高领，浅灰大衣", file: "outfit-14.png" },
  { name: "浅驼风衣，黑高领", file: "outfit-15.png" },
  { name: "奶白针织，深灰半裙", file: "outfit-16.png" },
  { name: "藏蓝衬衫，黑长裤", file: "outfit-17.png" },
  { name: "灰绿开衫，白内搭", file: "outfit-18.png" },
  { name: "米白衬衫，黑吊带", file: "outfit-19.png" },
  { name: "深棕大衣，奶油高领", file: "outfit-20.png" },
  { name: "浅蓝衬衫，藏青背心", file: "outfit-21.png" },
  { name: "白衬衫，浅灰长裙", file: "outfit-22.png" },
  { name: "暗红高领，黑长外套", file: "outfit-23.png" },
  { name: "燕麦毛衣，深橄榄裤", file: "outfit-24.png" },
  { name: "黑西装，白T恤", file: "outfit-25.png" },
  { name: "雾紫衬衫裙", file: "outfit-26.png" },
  { name: "深青针织，黑裙", file: "outfit-27.png" },
  { name: "卡其衬衫，炭灰马甲", file: "outfit-28.png" },
  { name: "银灰高领毛衣", file: "outfit-29.png" },
  { name: "墨蓝长风衣，白衬衫", file: "outfit-30.png" },
  { name: "黑色比基尼", file: "outfit-31.png" },
  { name: "白色比基尼", file: "outfit-32.png" },
  { name: "藏蓝连体泳衣", file: "outfit-33.png" },
  { name: "红色比基尼", file: "outfit-34.png" },
  { name: "黑色连体泳衣", file: "outfit-35.png" },
  { name: "碎花比基尼", file: "outfit-36.png" },
  { name: "墨绿比基尼", file: "outfit-37.png" },
  { name: "黑比基尼，白罩衫", file: "outfit-38.png" },
  { name: "条纹连体泳衣", file: "outfit-39.png" },
  { name: "雾蓝比基尼", file: "outfit-40.png" },
  { name: "黑吊带，牛仔短裤", file: "outfit-41.png" },
  { name: "黑色吊带裙", file: "outfit-42.png" },
  { name: "米色吊带，短裙", file: "outfit-43.png" },
  { name: "运动背心，黑短裤", file: "outfit-44.png" },
  { name: "奶油衬衫，黑裙", file: "outfit-45.png" },
  { name: "亚麻衬衫裙", file: "outfit-46.png" },
  { name: "黑背心，白短裤", file: "outfit-47.png" },
  { name: "灰上衣，黑打底裤", file: "outfit-48.png" },
  { name: "浅粉吊带裙", file: "outfit-49.png" },
  { name: "黑色挂脖裙", file: "outfit-50.png" },
  { name: "黑色吊带开叉短裙", file: "outfit-51.png" },
  { name: "红色露肩短裙", file: "outfit-52.png" },
  { name: "黑色吊带，短裙", file: "outfit-53.png" },
  { name: "白色系腰短上衣，热裤", file: "outfit-54.png" },
  { name: "黑色深V礼服", file: "outfit-55.png" },
  { name: "酒红比基尼", file: "outfit-56.png" },
  { name: "黑色连体衣，敞西装", file: "outfit-57.png" },
  { name: "香槟色吊带短裙", file: "outfit-58.png" },
  { name: "露背黑裙", file: "outfit-59.png" },
  { name: "黑色高开叉裙", file: "outfit-60.png" },
  { name: "红色抹胸短裙", file: "outfit-61.png" },
  { name: "粉色比基尼", file: "outfit-62.png" },
  { name: "黑色背心，短裤", file: "outfit-63.png" },
  { name: "白色深V衬衫裙", file: "outfit-64.png" },
  { name: "墨绿缎面短裙", file: "outfit-65.png" },
  { name: "黑色露肩毛衣，短裙", file: "outfit-66.png" },
  { name: "浅蓝比基尼", file: "outfit-67.png" },
  { name: "黑色立领开叉裙", file: "outfit-68.png" },
  { name: "白色抹胸，牛仔短裙", file: "outfit-69.png" },
  { name: "红色吊带，黑短裙", file: "outfit-70.png" },
  { name: "金色吊带短裙", file: "outfit-71.png" },
  { name: "黑比基尼，薄衬衫", file: "outfit-72.png" },
  { name: "紫色吊带短裙", file: "outfit-73.png" },
  { name: "白色露背裙", file: "outfit-74.png" },
  { name: "黑色短针织，包臀裙", file: "outfit-75.png" },
  { name: "珊瑚色比基尼", file: "outfit-76.png" },
  { name: "灰色吊带连体短裤", file: "outfit-77.png" },
  { name: "酒红开叉裙", file: "outfit-78.png" },
  { name: "黑色一字肩，长裤", file: "outfit-79.png" },
  { name: "米色V领裙", file: "outfit-80.png" },
  { name: "藏蓝比基尼", file: "outfit-81.png" },
  { name: "黑外套，吊带", file: "outfit-82.png" },
  { name: "粉色吊带短裙", file: "outfit-83.png" },
  { name: "白色高开叉裙", file: "outfit-84.png" },
  { name: "黑色抹胸连体裤", file: "outfit-85.png" },
  { name: "红色低领衬衫，黑裤", file: "outfit-86.png" },
  { name: "墨绿比基尼", file: "outfit-87.png" },
  { name: "黑色露肩毛衣短裙", file: "outfit-88.png" },
  { name: "香槟色开叉裙", file: "outfit-89.png" },
  { name: "条纹比基尼", file: "outfit-90.png" },
  { name: "黑色包臀吊带裙", file: "outfit-91.png" },
  { name: "白色短上衣，网球裙", file: "outfit-92.png" },
  { name: "深蓝露背礼服", file: "outfit-93.png" },
  { name: "粉比基尼，白衬衫", file: "outfit-94.png" },
  { name: "黑色丝绒吊带裙", file: "outfit-95.png" },
  { name: "红色高开叉裙", file: "outfit-96.png" },
  { name: "白色吊带短裙", file: "outfit-97.png" },
  { name: "黑吊带，滑落开衫", file: "outfit-98.png" },
  { name: "雾紫比基尼", file: "outfit-99.png" },
  { name: "黑色深V晚礼服", file: "outfit-100.png" }
];

function outfitForDate(dateStr, style) {
  const pool = style === "sexy" ? SEXY : style === "maid" ? MAID : style === "bodysuit" ? BODY : CAMPUS;
  const parts = dateStr.split("-").map(Number);
  const days = Math.floor(Date.UTC(parts[0], parts[1] - 1, parts[2]) / 86400000);
  const index = ((days % pool.length) + pool.length) % pool.length;
  return { index, outfit: pool[index] };
}

const CAMPUS = OUTFITS.slice(0, 30).concat([
  { name: "白衬衫，藏青背心，灰褶裙", file: "campus-01.png" },
  { name: "奶油开衫，海军褶裙", file: "campus-02.png" },
  { name: "浅蓝衬衫，卡其裤", file: "campus-03.png" },
  { name: "灰卫衣，深牛仔裤", file: "campus-04.png" },
  { name: "藏青西装，格裙", file: "campus-05.png" },
  { name: "米色毛衣，棕褶裙", file: "campus-06.png" },
  { name: "白 polo，藏青裙", file: "campus-07.png" },
  { name: "条纹衬衫，深牛仔裤", file: "campus-08.png" }
]);
const SEXY = OUTFITS.slice(30).concat([
  { name: "红色露肩短裙", file: "sexy-01.png" },
  { name: "黑色开叉短裙", file: "sexy-02.png" },
  { name: "黑色比基尼", file: "sexy-03.png" },
  { name: "红色抹胸短裙", file: "sexy-04.png" },
  { name: "白色比基尼", file: "sexy-05.png" },
  { name: "黑色露肩短裙", file: "sexy-06.png" },
  { name: "粉色比基尼", file: "sexy-07.png" },
  { name: "香槟色吊带短裙", file: "sexy-08.png" }
]);
const MAID = [
  { name: "黑色女仆裙", file: "maid-01.png" },
  { name: "黑裙白围裙", file: "maid-02.png" },
  { name: "暗红女仆裙", file: "maid-03.png" },
  { name: "藏青女仆裙", file: "maid-04.png" },
  { name: "短袖女仆裙", file: "maid-05.png" },
  { name: "长围裙女仆裙", file: "maid-06.png" },
  { name: "灰色女仆裙", file: "maid-07.png" },
  { name: "荷叶边围裙女仆裙", file: "maid-08.png" }
];
const BODY = [
  { name: "黑色长袖紧身衣", file: "bodysuit-01.png" },
  { name: "白色长袖紧身衣", file: "bodysuit-02.png" },
  { name: "黑色无袖紧身衣", file: "bodysuit-03.png" },
  { name: "灰色长袖紧身衣", file: "bodysuit-04.png" },
  { name: "暗红长袖紧身衣", file: "bodysuit-05.png" },
  { name: "藏蓝长袖紧身衣", file: "bodysuit-06.png" },
  { name: "棕色长袖紧身衣", file: "bodysuit-07.png" },
  { name: "炭灰长袖紧身衣", file: "bodysuit-08.png" }
];
